name: proptimus-raphan
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.2=py313hfc0e8ea_100
  - anaconda-auth=0.8.6=py313h06a4308_0
  - anaconda-cli-base=0.5.2=py313h06a4308_0
  - annotated-types=0.6.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - biopython=1.85=py313h07c4f96_2
  - boltons=25.0.0=py313h06a4308_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313h06a4308_0
  - colorama=0.4.6=py313h06a4308_0
  - conda=25.9.1=py313h78bf25f_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313h06a4308_1
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.12.0=py313h06a4308_0
  - contourpy=1.3.3=py313h7037e92_2
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=45.0.5=py313hea9ce0a_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h5bd4931_0
  - dftd4=3.6.0=hf49bc11_0
  - distro=1.9.0=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.60.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozendict=2.4.2=py313h06a4308_0
  - greenlet=3.2.4=py313h7033f15_1
  - icu=75.1=he02047a_0
  - idna=3.7=py313h06a4308_0
  - jaraco.classes=3.4.0=py313h06a4308_0
  - jaraco.context=6.0.0=py313h06a4308_0
  - jaraco.functools=4.1.0=py313h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - keyring=25.6.0=py313h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=hadbb8c3_0
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libboost=1.86.0=hb8260a3_2
  - libboost-python=1.86.0=py313hfaae9d9_4
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=3.0.0=1
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - librdkit=2025.09.1=h3c5c181_1
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hb346dea_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h280c20c_1002
  - markdown-it-py=2.2.0=py313h06a4308_1
  - matplotlib-base=3.10.7=py313h683a580_0
  - mctc-lib=0.3.2=h3b12eaf_1
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.3.1=py313h06a4308_0
  - more-itertools=10.3.0=py313h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - numpy=2.3.4=py313hf6604e3_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=py313h06a4308_0
  - pandas=2.3.3=py313h08cd8bf_1
  - pcre2=10.46=h1321c63_0
  - pillow=11.3.0=py313ha492abd_3
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h54a6638_1
  - pkce=1.0.3=py313h06a4308_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycairo=1.28.0=py313h3f29d12_1
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313h06a4308_0
  - pydantic-core=2.33.2=py313hc6f7160_0
  - pydantic-settings=2.6.1=py313h06a4308_0
  - pygments=2.19.1=py313h06a4308_0
  - pyjwt=2.10.1=py313h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.9=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py313h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - rdkit=2025.09.1=py313h66a1ddb_1
  - readchar=4.0.5=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - reportlab=4.4.4=py313h07c4f96_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.4=py313h06a4308_0
  - rich=13.9.4=py313h06a4308_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - secretstorage=3.3.1=py313h06a4308_1
  - semver=3.0.2=py313h06a4308_1
  - setuptools=78.1.1=py313h06a4308_0
  - shellingham=1.5.0=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - simple-dftd3=1.0.0=hd59d2e7_0
  - six=1.17.0=pyhe01879c_1
  - spdlog=1.11.0=hdb19cb5_0
  - sqlalchemy=2.0.44=py313h07c4f96_0
  - sqlite=3.50.4=hbc0de68_0
  - tblite=0.3.0=hf49bc11_1
  - tk=8.6.15=h54e0aa7_0
  - toml-f=0.4.2=h3b12eaf_2
  - tomli=2.2.1=py313h06a4308_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.1=py313h06a4308_0
  - typer=0.9.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing-inspection=0.4.0=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xtb=6.6.1=hf49bc11_0
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - -e .
